### ISSUE TITLE
Cannot read property 'apply' of null

### ISSUE THREAD

**Issue by ha7ilm** [tomgrooffer/icons-loader#4]
I'm getting this error with `webpack@2.2.1`:

```
 webpack                                    
/home/pcfl/.nvm/versions/node/v6.2.1/lib/node_modules/webpack/bin/webpack.js:315
		throw e;
		^

TypeError: Cannot read property 'apply' of null
    at IconsPlugin.apply (/home/pcfl/gflow/project/node_modules/icons-loader/IconsPlugin.js:38:30)
    at Compiler.apply (/home/pcfl/.nvm/versions/node/v6.2.1/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:306:16)
    at webpack (/home/pcfl/.nvm/versions/node/v6.2.1/lib/node_modules/webpack/lib/webpack.js:32:19)
    at processOptions (/home/pcfl/.nvm/versions/node/v6.2.1/lib/node_modules/webpack/bin/webpack.js:305:14)
    at Object.<anonymous> (/home/pcfl/.nvm/versions/node/v6.2.1/lib/node_modules/webpack/bin/webpack.js:363:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3
```

**Comment by C3PablO** [comment]
Seems like the loader doesn't work with webpack2 at all
